import os
import json
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel
from rich.table import Table

console = Console()

def run_wizard():
    console.print(Panel("[bold orange1]SKELETEN // PHASE_00_INTENT // WIZARD[/bold orange1]\n[italic]The architectural blueprint starts here.[/italic]", border_style="orange1"))
    
    intent = {}
    
    # 1. Project Identity
    intent['project_name'] = Prompt.ask("[bold]Project Name[/bold]", default="my-skeleten-app")
    intent['description'] = Prompt.ask("[bold]Primary Goal / Description[/bold]")
    
    # 2. Tech Stack
    intent['stack'] = Prompt.ask("[bold]Core Tech Stack[/bold] (e.g., Node.js, Python, React)", default="Python")
    
    # 3. Domain Entities
    entities_str = Prompt.ask("[bold]Key Domain Entities[/bold] (comma separated, e.g., Users, Auth, Payments)")
    intent['entities'] = [e.strip() for e in entities_str.split(",") if e.strip()]
    
    # 4. Success Criteria
    intent['success_metric'] = Prompt.ask("[bold]Key Success Metric[/bold]", default="100% Documentation Sync")

    # 5. Intent vs Reality Mapping (Pre-coding expectations)
    console.print("\n[bold orange1]ARCHITECTURAL PROMISES[/bold orange1]")
    components = []
    while True:
        comp_name = Prompt.ask("[cyan]Component Name[/cyan] (or press Enter to finish)", default="")
        if not comp_name:
            break
        comp_desc = Prompt.ask(f"[italic]What should {comp_name} do?[/italic]")
        components.append({"name": comp_name, "intent": comp_desc})
    
    intent['components'] = components

    # Save outputs
    os.makedirs("dist", exist_ok=True)
    
    # JSON Intent Matrix
    with open("dist/skeleten_intent.json", "w") as f:
        json.dump(intent, f, indent=4)
        
    # Markdown Design Spec
    spec_md = f"""# SKELETEN DESIGN SPEC // {intent['project_name']}
    
## MISSION
{intent['description']}

## TECH STACK
- {intent['stack']}

## CORE ENTITIES
{chr(10).join(['- ' + e for e in intent['entities']])}

## ARCHITECTURAL COMPONENTS & INTENTS
| Component | Stated Intent |
|-----------|---------------|
{chr(10).join([f"| {c['name']} | {c['intent']} |" for c in intent['components']])}

## SUCCESS METRIC
{intent['success_metric']}

---
*Generated by SKELETEN Phase 00 Wizard*
"""
    with open("SKELETEN_DESIGN_SPEC.md", "w") as f:
        f.write(spec_md)

    console.print("\n[bold green][+] SKELETEN_DESIGN_SPEC.md generated.[/bold green]")
    console.print("[bold green][+] dist/skeleten_intent.json established as Ground Truth.[/bold green]")
    console.print(Panel("[bold white]Phase 00 COMPLETE. SKELETEN is now watching your repository for drift against these promises.[/bold white]", style="bg:orange1"))

if __name__ == "__main__":
    run_wizard()
